### ISSUE TITLE
Idle project / organization?

### ISSUE THREAD

**Issue by kennu** [clouden/Clouden_Box#1]
Hello, sorry to bother through an issue, but I was wondering if this organization name is idle and could be used for something else? We have an organization called Clouden in NPM and it would be nice to use this name on GitHub. But if you need it for something else, no problem.

**Comment by themakerbro** [comment]
No worries. The project (http://clouden.io/) is currently idle, but after securing a few domains/usernames on different platforms I'd be up for keeping it. I'm open to listening to monetary offers if your project has a budget for it, however. Best of luck either way!
